/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Task } from './task';


export interface DashboardTasks { 
    dueToday: Array<Task>;
    overdue: Array<Task>;
    completedTodayCount: number;
    totalActive: number;
    doneCount: number;
    completionPercent: number;
}

