/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Plan } from './plan';


export interface DashboardPlans { 
    inProgress: Array<Plan>;
    upcomingCount: number;
    completedCount: number;
}

