/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Habit } from './habit';


export interface DashboardHabits { 
    today: Array<Habit>;
    activeCount: number;
    completedTodayCount: number;
}

