/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HabitCompletionRequest { 
    /**
     * Defaults to today; must not be in the future
     */
    date?: string | null;
}

