/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HabitCompletion { 
    id: number;
    habitId: number;
    completionDate: string;
    createdAt: string;
}

