/**
 * QuickFlow API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlanItemSourceType } from './planItemSourceType';


export interface PlanItemSource { 
    sourceType: PlanItemSourceType;
    sourceId: number;
}
export namespace PlanItemSource {
}


